### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by xblitz** [sensu/uchiwa-chef#54]
can the version be bumped so we get the new repository changes?

**Comment by xblitz** [comment]
is there a blocker for the version bump? the commit is already in, we just need a version bump so that we get the newer uchiwa version

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/uchiwa-chef/pull/55.

**Comment by palourde** [comment]
Fixed by https://github.com/sensu/uchiwa-chef/commit/b1cc5f1ed06b27a22eb2a1867058b8d0c8178ec4.

**Comment by xblitz** [comment]
merci!
