### ISSUE TITLE
apt recipe still included

### ISSUE THREAD

**Issue by bleything** [sensu/uchiwa-chef#66]
[The repo recipe](https://github.com/sensu/uchiwa-chef/blob/master/recipes/repo.rb#L28) still tries to `include_recipe 'apt'`. I suspect this got missed during #65? I can send you a tiny PR if you like!

**Comment by majormoses** [comment]
Yup looks like it. I would love a PR to fix it.

fyi @tas50

**Comment by bleything** [comment]
Resolved by #67.
